/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hong3_testproject_JniUtil */

#ifndef _Included_com_example_hong3_testproject_JniUtil
#define _Included_com_example_hong3_testproject_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hong3_testproject_JniUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hong3_testproject_JniUtil_getStringFromNative
  (JNIEnv *, jobject){
  return "This just a test for Android Studio NDK JNI developer!";
  };

#ifdef __cplusplus
}
#endif
#endif